### ISSUE TITLE
This link is not working; replacement?

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-526-template#3]
https://github.com/Watts-College/cpp-526-template/blob/bde25101c47927f3c0c4b50753c477c2e0b23228/labs/final-project-instructions.rmd#L57

**Comment by jacobtnyoung** [comment]
@lecy is this the preferred way for me to ask questions about updates to the template?

**Comment by lecy** [comment]
Sure, this works. 

Go ahead and make changes if you have fixes or preferences. 

If you have questions about how something works then feel free to ping me in this way. Keeps each issue as discrete and manageable.
