### ISSUE TITLE
Missing link for schedule.md file

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-526-template#4]
On line 508 of the schedule.md file, the https://ds4ps.org/Data-Science-Class/DATA/syr_parcels.html page is redirecting to a 404. @lecy do you see the issue?

Also, is there a way I can make comments/raise issues in the actual file?

**Comment by lecy** [comment]
That file - syr_pacels.rmd/html has been added to the labs folder. 

The link should be changed to:

COURSE_URL/syr_parcels.html 

It should work then.

**Comment by lecy** [comment]
> Also, is there a way I can make comments/raise issues in the actual file?

I am not sure I understand this question.

**Comment by jacobtnyoung** [comment]
Thanks for fixing that. Got it.

**Comment by jacobtnyoung** [comment]
> > Also, is there a way I can make comments/raise issues in the actual file?
> 
> I am not sure I understand this question.

I wasn't clear. Instead of saying "file x.md needs to be fixed at line 508" is there a way that I can go to that file and make a comment or note that there is a problem? For example, put a comment on line 508 of that file? That way, it takes you right to where the issue is instead of having to put instructions here.

Does that make sense @lecy?

**Comment by lecy** [comment]
You can do a pull request. Edit the file (flag the issue where it’s broken) then initiate a pull request for that file. 

You could also do an edit, then send the edit history from that commit. It shows the differenced view so would highlight the specific line that way. 

At the top of each file on GitHub it will list the most recent edit. Can grab that link.

**Comment by lecy** [comment]
https://github.com/Watts-College/cpp-526-template/commit/3a4d098cfd3e512ce2e3c75192dac3ca09509de1

**Comment by jacobtnyoung** [comment]
oh cool. Thanks!
